spring:
  application:
    name: Xunibi-backend
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/xunibi?serverTimezone=GMT%2B8"
    username: root
    password: 12345678
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.xunibibackend.entity